import { describe, expect, it } from "vitest";
import { mulberry32 } from "../rng.ts";

/**
 * The seeded PRNG, pinned to literals.
 *
 * This is a parity contract, not an implementation detail. The solver's
 * captured baseline was generated by this exact stream, so any edit that
 * changes the arithmetic - a different constant, a shifted rounding, swapping
 * `Math.imul` for `*` - silently invalidates roughly 1.6 MB of precomputed
 * output. Without literals here, that shows up as a parity job disagreeing
 * about layouts, which is a long way from the line that caused it.
 *
 * The numbers below were produced by the current implementation. They are the
 * baseline's definition of correct, so a failure here means "you changed the
 * generator", and the fix is either to revert the change or to regenerate the
 * precompute deliberately. It is never to update these literals to match.
 */
describe("mulberry32", () => {
  it("produces its documented stream for a known seed", () => {
    const rng = mulberry32(12345);
    const first8 = Array.from({ length: 8 }, () => rng.next());

    expect(first8).toEqual([
      0.9797282677609473,
      0.3067522644996643,
      0.484205421525985,
      0.817934412509203,
      0.5094283693470061,
      0.34747186047025025,
      0.07375754183158278,
      0.7663964673411101,
    ]);
  });

  it("gives every value in [0, 1)", () => {
    const rng = mulberry32(20260809);
    for (let i = 0; i < 5000; i++) {
      const v = rng.next();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
  });

  it("keeps two instances of the same seed in lockstep", () => {
    const a = mulberry32(4242);
    const b = mulberry32(4242);
    for (let i = 0; i < 1000; i++) expect(a.next()).toBe(b.next());
  });

  it("gives different seeds different streams", () => {
    const a = mulberry32(1);
    const b = mulberry32(2);
    const sameCount = Array.from({ length: 200 }, () => a.next() === b.next()).filter(Boolean).length;
    expect(sameCount).toBe(0);
  });

  it("survives a zero seed rather than degenerating", () => {
    const rng = mulberry32(0);
    expect(rng.next()).toBe(0.26642920868471265);
    // A stuck generator would repeat; the second draw proves the state moved.
    expect(rng.next()).toBe(0.0003297457005828619);
  });

  describe("int", () => {
    it("stays inside [0, n) and never returns n", () => {
      const rng = mulberry32(777);
      for (const n of [1, 2, 3, 7, 16, 100]) {
        for (let i = 0; i < 2000; i++) {
          const v = rng.int(n);
          expect(Number.isInteger(v)).toBe(true);
          expect(v).toBeGreaterThanOrEqual(0);
          expect(v).toBeLessThan(n);
          expect(v).not.toBe(n);
        }
      }
    });

    it("returns 0 for a degenerate bound instead of NaN or a negative", () => {
      const rng = mulberry32(5);
      expect(rng.int(0)).toBe(0);
      expect(rng.int(-1)).toBe(0);
      expect(rng.int(-100)).toBe(0);
    });

    it("does not consume the stream when the bound is degenerate", () => {
      // `int` short-circuits before calling next(), so a zero bound must leave
      // the next draw exactly where an untouched generator would have it.
      const consumed = mulberry32(31337);
      consumed.int(0);
      consumed.int(-5);
      expect(consumed.next()).toBe(mulberry32(31337).next());
    });

    it("produces its documented integer stream for a known seed", () => {
      const rng = mulberry32(999);
      expect(Array.from({ length: 8 }, () => rng.int(7))).toEqual([6, 4, 2, 5, 3, 4, 0, 4]);
    });
  });
});
